// src/types/monthlyPayments.types.ts
// 📝 NUEVOS TIPOS PARA PAGOS MENSUALES

export interface MonthlyPaymentRecord {
  id?: string;
  memberId: string;
  memberName: string;
  year: number;
  month: number; // 1-12
  createdAt: any; // Firebase Timestamp
  updatedAt?: any;
  
  // Detalles de las actividades del socio para este mes
  activities: { [activityId: string]: MonthlyActivityPayment };
  
  // Totales calculados
  totalCost: number;
  totalPaid: number;
  totalPending: number;
}

export interface MonthlyActivityPayment {
  activityId: string;
  activityName: string;
  cost: number;
  status: 'pending' | 'paid' | 'overdue';
  dueDate: string; // YYYY-MM-DD
  paidDate?: string; // YYYY-MM-DD
  transactionId?: string;
  
  // Info adicional
  membershipId: string;
  autoGenerated: boolean; // Si fue creado automáticamente
}

export interface MonthlySummary {
  year: number;
  month: number;
  totalMembers: number;
  totalToCollect: number;
  totalCollected: number;
  totalPending: number;
  membersWithDebt: number;
  membersUpToDate: number;
  
  // Breakdown por actividad
  activitiesBreakdown: {
    [activityName: string]: {
      members: number;
      totalCost: number;
      collected: number;
      pending: number;
    };
  };
}

// Para la automatización
export interface AutoGenerationConfig {
  enabled: boolean;
  dayOfMonth: number; // 1-28
  excludeInactiveMembers: boolean;
  onlyAutoRenewalMemberships: boolean;
  lastProcessedMonth?: string; // 'YYYY-MM'
}

// Para el dashboard
export interface MonthlyPaymentListItem {
  memberId: string;
  memberName: string;
  memberEmail?: string;
  totalCost: number;
  totalPaid: number;
  totalPending: number;
  activitiesCount: number;
  activitiesPaid: number;
  activitiesPending: number;
  isOverdue: boolean;
  daysOverdue: number;
  
  // Detalles de actividades para mostrar
  activities: {
    name: string;
    cost: number;
    status: 'pending' | 'paid' | 'overdue';
    dueDate: string;
  }[];
}

// Función auxiliar para importar useAuth
export type PaymentMethod = 'cash' | 'transfer' | 'card';